#! /bin/bash
#
# ipfixcol	IPFIX collector
#
# chkconfig: - 90 60
# description: ipfixcol is an IPFIX collector
# processname: ipfixcol
# pidfile: /var/run/ipfixcol.pid
# Source function library.
. /etc/init.d/functions

RETVAL=0

# See how we were called.
  
ipfixcol="ipfixcol"
prog="ipfixcol"
params=" -v 2 -d -c /etc/ipfixcol/startup-udp-4739.xml"
params=" -v 2 -d"
pidfile="/var/run/ipfixcol.pid"


start() {
	echo -n $"Starting $prog: "

	# Check that ipfixcol is not running
	status -p $pidfile $ipfixcol > /dev/null
	if [ $? -eq 0 ]; then
		echo -n "already running..."
		echo_failure
		echo
		return 1
	fi

	# Start ipfixcol
	daemon --pidfile=${pidfile} $ipfixcol "$params"
	RETVAL=$?
	echo

	# Create pid file when the start was successful
	if [ $RETVAL -eq 0 ]; then
		echo `ps ax | grep -E "ipfixcol -v 2 -d$" | cut --delimiter=' ' -f 1` > $pidfile
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "

	killproc -p $pidfile $ipfixcol
	RETVAL=$?
	echo
	return $RETVAL
}	

rhstatus() {
	status -p $pidfile $ipfixcol
}	

restart() {
  	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  status)
  	rhstatus
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit $?
