/**
 * \file printer.h
 * \author Petr Velan <petr.velan@cesnet.cz>
 * \brief Header of class for printing fastbit tables
 *
 * Copyright (C) 2011 CESNET, z.s.p.o.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name of the Company nor the names of its contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * ALTERNATIVELY, provided that this notice is retained in full, this
 * product may be distributed under the terms of the GNU General Public
 * License (GPL) version 2 or later, in which case the provisions
 * of the GPL apply INSTEAD OF those given above.
 *
 * This software is provided ``as is, and any express or implied
 * warranties, including, but not limited to, the implied warranties of
 * merchantability and fitness for a particular purpose are disclaimed.
 * In no event shall the company or contributors be liable for any
 * direct, indirect, incidental, special, exemplary, or consequential
 * damages (including, but not limited to, procurement of substitute
 * goods or services; loss of use, data, or profits; or business
 * interruption) however caused and on any theory of liability, whether
 * in contract, strict liability, or tort (including negligence or
 * otherwise) arising in any way out of the use of this software, even
 * if advised of the possibility of such damage.
 *
 */

#ifndef PRINTER_H_
#define PRINTER_H_

#include <cstdio>
#include <vector>
#include <map>
#include <iostream>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <ibis.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <regex.h>
/* this header must be generated by ./tools/generate_protocols.sh script */
#include "protocols.h"

#include "configuration.h"

/**
 * \brief Namespace of the ipfixdump utility
 */
namespace ipfixdump {
/* TODO set something meaningful */
#define BYTE_STRLEN 6 /*real 3*/
#define SHORT_STRLEN 6 /*real 5*/
#define INT_STRLEN 9
#define LONG_STRLEN 10
#define FLOAT_STRLEN 10
#define DOUBLE_STRLEN 10
#define IPV6_STRLEN 30
#define PROTOCOL_STRLEN 10
#define COLUMN_SEPARATOR " "
#define NULL_STR "NULL";

typedef struct {
	std::string name;
	ibis::TYPE_T type;
	int width;
	int align; /**< 1 left, 0 right */
	std::string semantics;
} columnInfo;

typedef std::vector<columnInfo*> columnInfoVector;

/**
 * \brief Class printing tables
 *
 * Handles output formatting
 */
class printer {
private:

	/**
	 * \brief print one row
	 *
	 * @param cur cursor poiting to the row
	 */
	void printRow(ibis::table::cursor *cur);

	/**
	 * \brief Print table header
	 */
	void printHeader();

	/**
	 * \brief Print formatted IPv4 address
	 */
	void printIPv4(uint32_t address);

	/**
	 * \brief Print formatted IPv6 address
	 */
	void printIPv6(uint64_t part1, uint64_t part2);

	/**
	 * \brief Print formatted timestamp
	 */
	void printTimestamp(uint64_t timestamp);

	/**
	 * \brief Print element specified by colInfo of current line base on type
	 *
	 * @param cur Cursor pointing to current line
	 * @param colInfo columnInfo structure specifying the element
	 * @return 0 on success (element found and printed), non-zero otherwise
	 */
	int printByType(ibis::table::cursor *cur, columnInfo *colInfo);

	/**
	 * \brief Returns string length based on type (for formatting)
	 *
	 * @param type column type
	 * @return length of the string with specified type
	 */
	int getStrLengthByType(ibis::TYPE_T type);

	/**
	 * \brief Returns string length based on name(for formatting)
	 *
	 * @param name column name
	 * @return length of the string with specified type
	 */
	int getStrLengthByName(std::string name);

	/**
	 * \brief Returns string length based on its semantics
	 *
	 * @param semantics
	 * @return length of the string with specified semantics
	 */
	int getStrLengthBySemantics(std::string semantics);

	/**
	 * \brief Parse output format
	 */
	void parseFormat();

	/**
	 * \brief Reads semantics string for specified element
	 *
	 * @param name Element name
	 * @return
	 */
	std::string getSemantics(std::string name);

	/**
	 * \brief Private default constructor
	 */
	printer();

	std::ostream &out; /**< Stream to write to */
	configuration &conf; /**< program configuration */

	tableVector tables; /**< tables to print */
	std::vector<columnInfoVector> colInfos; /**< Printed table col info*/
	ibis::table::namesTypes namesTypes; /**< assoc. array of names and types */

public:

	/**
	 * \brief Constructor
	 *
	 * @param out ostream to print to
	 * @param conf configuration class
	 */
	printer(std::ostream &out, configuration &conf);

	/**
	 * \brief Prints output in specified format
	 *
	 * This is the real printer function, public ones only
	 * set tables to work with and call this.
	 *
	 * @param limit print max limit rows (0 = all)
	 * @return 0 on success, non-zero otherwise
	 */
	int print(uint64_t limit);

	/**
	 * \brief Adds table to list of tables to print
	 *
	 * @param table table to be added
	 */
	void addTable(ibis::table *table);

	/**
	 * \brief Add tables to list of tables to print
	 *
	 * @param tables vector of tables to be added
	 */
	void addTables(tableVector &tables);

	/**
	 * \brief clear list of tables to print
	 *
	 * @return Vector of tables preciously stored
	 */
	tableVector clearTables();
};

}  // namespace ipfixdump


#endif /* PRINTER_H_ */
